services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 6022:5432
    env_file:
      - ./back-end/.env
    volumes:
      - pg:/var/lib/postgresql/data

  node_back-end:
    container_name: node_back-end
    build: ./back-end
    restart: always
    ports:
      - 5009:5000
    depends_on:
      - db
    env_file:
      - ./back-end/.env
volumes:
  pg:
      