services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 6022:5432
    env_file:
      - ./back-end/.env
    volumes:
      - pg:/var/lib/postgresql/data

  node_back-end:
    container_name: node_back-end
    build: ./back-end
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - ./back-end/.env

  node_front-end:
    container_name: node_front-end
    build: ./front-end
    volumes:
      - build_react:/var/www/html

  nginx:
    container_name: nginx
    build: ./front-end/nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - db
      - node_back-end
      - node_front-end

volumes:
  pg:
  build_react:
      